// <auto-generated />
using EBSystem.Order.API.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBSystem.Order.API.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20220403032746_payment_type")]
    partial class payment_type
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EBSystem.Order.API.Entities.PaymentType", b =>
                {
                    b.Property<long>("paymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("paymentTypeId"), 1L, 1);

                    b.Property<string>("paymentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentTypeId");

                    b.ToTable("paymentTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
